---
title: "Lab 01 - Hello R"
author: "Student Name"
date: "1/19/2018"
output:
  html_notebook:
    fig_height: 4
    fig_width: 6
    number_sections: yes
    theme: paper
    toc: yes
---

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```


### Exercise 1

- The datasaurus_dozen dataset has 1846 rows and 3 columns.
- The variables are: dataset, x, y

### Exercise 2

First let's plot the data in the dino dataset:

```{r plot-dino, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")

ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

And next calculate the correlation between `x` and `y` in this dataset:

```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```

### Exercise 3

Blah blah blah...

```{r plot-star}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")

ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

ok

```{r cor-star}
star_data %>%
  summarize(r = cor(x, y))
```

### Exercise 4


```{r plot-circle}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")

ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r cor-circle}
circle_data %>%
  summarize(r = cor(x, y))
```

### Exercise 5

```{r plot-allDatasets, fig.height=12, fig.width=6}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
  geom_point()+
  facet_wrap(~ dataset, ncol = 3) +
  theme(legend.position = "none")
```


```{r cor-allDatasets}
datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x, y), mean(x), var(x), mean(y), var(y)) %>%
  print(13)
```

